# 1. Usa una imagen base oficial de Python
FROM python:3.10-slim


COPY requirements.txt app/requirements.txt  
# 2. Establece el directorio de trabajo en la carpeta actual
WORKDIR /app

# 4. Instala las dependencias necesarias
RUN pip install -r requirements.txt

# 5. Copia todo el código del frontend
COPY . /app

# 6. Expone el puerto 8501
EXPOSE 8501

ENTRYPOINT ["streamlit","run"]

# 7. Define el comando para iniciar Streamlit
CMD ["main.py"]
